- name: Single Branch Pipeline
  ansible.builtin.include_tasks:
    file: sjobs.yml
  loop: "{{sjobs}}"

- name: Multi-Branch Pipeline
  ansible.builtin.include_tasks:
    file: sjobs.yml
  loop: "{{mjobs}}"