sjobs:
  - { git_url:https://github.com/jkesarwani123/roboshop-ansible.git, job_name: roboshop-ansible-seed }
  - { git_url:https://github.com/jkesarwani123/project-terra.git, job_name: roboshop-terraform-seed }